volumes:
  db:
  redis:
  cert_cache:
  soundboard:


networks:
  default:


services:

  nirn: 
    image: ghcr.io/germanoeich/nirn-proxy
    restart: unless-stopped
    networks:
      - default

  yagpdb:
    build:
      # We change context so that we can copy the local repo in during
      # development
      context: ../
      dockerfile: yagpdb_docker/Dockerfile.debug
    restart: unless-stopped
    depends_on:
      - nirn
      - redis
      - db
    networks:
      - default
    volumes:
      - cert_cache:/app/cert
      - soundboard:/app/soundboard
      - ..:/app/yagpdb
    ports:
      - '5000:5000'
      - '4000:4000'
      #- '5100-5999:5100-5999'
    env_file:
      - app.env
    security_opt:
      - "seccomp:unconfined"

  redis:
    image: docker.io/redis
    restart: unless-stopped
    networks:
      - default
    volumes:
      - redis:/data

  db:
    image: docker.io/postgres:11
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - default
    env_file:
      - db.env
