add-global-variants="true"
no-hooks="true"
no-tests="true"

[psql]
dbname="yagpdb"
host="localhost"
user="yagpdb"
pass="ihateducks"
sslmode="disable"
whitelist=["server_stats_periods", "server_stats_configs", "server_stats_member_periods"]