version: 2 # use CircleCI 2.0
jobs: # basic units of work in a run
  build: # runs not using Workflows must have a `build` job as entry point
    docker: # run the steps with Docker
      # CircleCI Go images available at: https://hub.docker.com/r/circleci/golang/
      - image: circleci/golang:1.14 #

    # directory where steps are run. Path must conform to the Go Workspace requirements
    working_directory: /go/src/github.com/jonas747/yagpdb

    steps: # steps that comprise the `build` job
      - checkout # check out source code to working directory
      # - run: mkdir -p $TEST_RESULTS # create the test results directory


      - restore_cache: # restores saved cache if no changes are detected since last run
      # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          keys:
            - v1-pkg-cache
     
      - run: 
          name: main yagpdb binary build
          command: |
            VERSION=$(git describe --tags)
            cd cmd/yagpdb
            go install -i -ldflags "-X github.com/jonas747/yagpdb/common.VERSION=${VERSION}"
            cd -
      - run: cd cmd/shardorchestrator && go install -i && cd -
      - run: cd cmd/capturepanics && go install -i && cd -

      - run: go test -v ./...

      - save_cache: # Store cache in the /go/pkg directory
          key: v1-pkg-cache
          paths:
            - "/go/pkg"

      - run:
          name: Prepare arifacts
          command: |
            mkdir -p cmd/yagpdb/templates/plugins
            cp */assets/* cmd/yagpdb/templates/plugins/

            tar -cvf misc_artifacts.tar cmd/yagpdb/templates/ cmd/yagpdb/static/
            
      - store_artifacts:
          path: misc_artifacts.tar
          destination: misc

      - store_artifacts:
          path: /go/bin/
          destination: binaries
