version: 2 # use CircleCI 2.0
jobs: # basic units of work in a run
  build: # runs not using Workflows must have a `build` job as entry point
    docker: # run the steps with Docker
      # CircleCI Go images available at: https://hub.docker.com/r/circleci/golang/
      - image: circleci/golang:1.12 #

    # directory where steps are run. Path must conform to the Go Workspace requirements
    working_directory: /go/src/github.com/jonas747/yagpdb

    steps: # steps that comprise the `build` job
      - checkout # check out source code to working directory
      # - run: mkdir -p $TEST_RESULTS # create the test results directory


      - restore_cache: # restores saved cache if no changes are detected since last run
      # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          keys:
            - v1-pkg-cache

      - run: git clone -b dgofork https://github.com/jonas747/dutil /go/src/github.com/jonas747/dutil
      - run: git clone -b dgofork https://github.com/jonas747/dshardmanager /go/src/github.com/jonas747/dshardmanager

      - run: go get -d -t ./...
      - run: go get -v -t github.com/jonas747/yagpdb/cmd/yagpdb # pull and build dependencies for the project
      - run: go get -v -t github.com/jonas747/yagpdb/cmd/shardorchestrator # pull and build dependencies for the project
      - run: go get -v -t github.com/jonas747/yagpdb/cmd/capturepanics # pull and build dependencies for the project

      - run: go test -v ./...

      - save_cache: # Store cache in the /go/pkg directory
          key: v1-pkg-cache
          paths:
            - "/go/pkg"

      - run:
          name: Prepare arifacts
          command: |
            mkdir -p cmd/yagpdb/templates/plugins
            cp */assets/* cmd/yagpdb/templates/plugins/

            mkdir tmp_artifacts
            cp -r cmd/yagpdb/templates tmp_artifacts/
            cp -r cmd/yagpdb/static tmp_artifacts/

            tar -cvf misc_artifacts.tar tmp_artifacts/
            
      - store_artifacts:
          path: misc_artifacts.tar
          destination: misc

      - store_artifacts:
          path: /go/bin/
          destination: binaries