add-global-variants = true
no-hooks = true
no-tests = true

[psql]
dbname = "yagpdb"
host = "localhost"
user="yagpdb"
pass="ihateducks"
sslmode = "disable"
whitelist = ["youtube_channel_subscriptions", "youtube_announcements"]

[auto-columns]
created = "created_at"
updated = "updated_at"
